// layout.js
import ClientLayout from "./components/common/ClientLayout";
import "./globals.css";

export const metadata = {
  title: "Vanikas Makeover",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ClientLayout>{children}</ClientLayout> {/* Use ClientLayout here */}
      </body>
    </html>
  );
}
